services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=
      - API_KEY_FIREBASE=
      - AUTHDOMAIN=
      - PROJECTID=
      - STORAGEBUCKET=
      - MESSAGINGSENDERID=
      - APPID=
      - MEASUREMENTID=
      - NODE_ENV=production
    ports:
      - "3000:3000"
   
    volumes:
      - .:/app  # Monta o diretório atual no container 
    networks:
      - webnet  # Conecta o container a uma rede chamada 'webnet'
networks:
    webnet:
     driver: bridge