# Usa uma imagem Node.js
FROM node:20.18.0-alpine

# Define o diretório de trabalho dentro do contêiner
WORKDIR /app

# Copia os arquivos package.json e package-lock.json para instalar dependências
COPY package*.json ./ 

# Instala as dependências do projeto
RUN npm install --omit=dev

# Copia o arquivo do serviço para dentro do contêiner
COPY ./src/services/userService.js ./userService.js

# Expõe a porta do serviço
EXPOSE 5003

# Comando para iniciar o serviço
CMD ["node", "userService.js"]